# Generated by Django 3.1.1 on 2026-01-30 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaperAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CAT1', 'CAT 1'), ('CAT2', 'CAT 2'), ('ENDSEM', 'End Semester'), ('REEXAM', 'Re-Examination'), ('ARREAR', 'Arrear Exam'), ('MODEL', 'Model Exam')], max_length=10)),
                ('regulation', models.CharField(choices=[('R2021', 'Regulation 2021'), ('R2017', 'Regulation 2017'), ('R2013', 'Regulation 2013')], default='R2021', max_length=10)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('deadline', models.DateField()),
                ('max_marks', models.IntegerField(default=100)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=3.0, max_digits=3)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for question paper preparation', null=True)),
                ('syllabus_units', models.CharField(blank=True, help_text='Units to cover, e.g., "1,2,3,4,5" or "All"', max_length=50, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVISION_REQUIRED', 'Revision Required')], default='ASSIGNED', max_length=20)),
                ('question_paper', models.FileField(blank=True, null=True, upload_to='question_papers/')),
                ('answer_key', models.FileField(blank=True, null=True, upload_to='answer_keys/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('faculty_remarks', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.academicyear')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_qp_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qp_assignments', to='main_app.faculty_profile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qp_assignments', to='main_app.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_qp_assignments', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.semester')),
            ],
            options={
                'verbose_name': 'Question Paper Assignment',
                'verbose_name_plural': 'Question Paper Assignments',
                'ordering': ['-created_at'],
                'unique_together': {('course', 'academic_year', 'semester', 'exam_type', 'regulation')},
            },
        ),
    ]
