# Generated by Django 3.1.1 on 2026-01-30 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_questionpaperassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionpaperassignment',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.regulation'),
        ),
    ]
