# Generated by Django 3.1.1 on 2026-01-31 18:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_timeslot_timetable_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., CSE, CSE-OR, CSE-BDA, SE', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full program name', max_length=200)),
                ('degree', models.CharField(choices=[('BE', 'B.E.'), ('BTECH', 'B.Tech.'), ('ME', 'M.E.'), ('MTECH', 'M.Tech.'), ('MS', 'M.S.'), ('PHD', 'Ph.D.')], default='BE', max_length=10)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('PHD', 'Ph.D.')], default='UG', max_length=5)),
                ('specialization', models.CharField(blank=True, help_text='e.g., Operations Research, Big Data Analytics', max_length=200, null=True)),
                ('duration_years', models.IntegerField(default=4, help_text='Program duration in years', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('total_semesters', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('regulations', models.ManyToManyField(blank=True, help_text='Regulations under which this program is offered', related_name='programs', to='main_app.Regulation')),
            ],
            options={
                'verbose_name': 'Academic Program',
                'verbose_name_plural': 'Academic Programs',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='student_profile',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Specific program like M.E. CSE, M.E. Software Engineering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main_app.program', verbose_name='Academic Program'),
        ),
    ]
