# Generated by Django 3.1.1 on 2026-01-31 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20260131_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_profile',
            name='register_no',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Register number must be exactly 10 digits', regex='^\\d{10}$')], verbose_name='Register Number'),
        ),
    ]
