# Generated by Django 6.0.1 on 2026-02-02 14:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_login_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student_profile",
            name="program",
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="register_no",
            field=models.CharField(
                max_length=12,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Register number must be exactly 12 digits",
                        regex="^\\d{12}$",
                    )
                ],
                verbose_name="Register Number",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="lab_end_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_end_entries",
                to="main_app.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="timetableentry",
            name="special_note",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
