# Generated by Django 6.0.1 on 2026-02-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_remove_student_profile_program_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account_user",
            name="is_staff",
        ),
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("PCC", "Professional Core Course"),
                            ("ESC", "Engineering Science Course"),
                            ("PEC", "Professional Elective Course"),
                            ("HSMC", "Humanities Science and Management Course"),
                            ("ETC", "Emerging Technology Course"),
                            ("SDC", "Skill Development Course"),
                            ("OEC", "Open Elective Course"),
                            ("UC", "University Course"),
                            ("SLC", "Self Learning Course"),
                        ],
                        help_text="Course category code (e.g., PCC, ESC)",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Custom description (optional, defaults to choice label)",
                        max_length=200,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_categories",
                        to="main_app.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Category",
                "verbose_name_plural": "Course Categories",
                "ordering": ["regulation", "code"],
                "unique_together": {("regulation", "code")},
            },
        ),
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Course category (PCC, ESC, PEC, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="main_app.coursecategory",
            ),
        ),
    ]
