# Generated by Django 6.0.1 on 2026-02-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_add_course_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursecategory",
            name="code",
            field=models.CharField(
                help_text="Course category code (e.g., PCC, ESC, or custom)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="coursecategory",
            name="description",
            field=models.CharField(
                blank=True, help_text="Category description", max_length=200
            ),
        ),
    ]
