# Generated by Django 4.2.9 on 2026-02-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_qpquestion_structuredquestionpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpquestion',
            name='answer',
            field=models.TextField(blank=True, help_text='Selected answer for answer key'),
        ),
    ]
