# Generated by Django 6.0.1 on 2026-02-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_allow_custom_course_categories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicyear",
            name="is_current",
        ),
    ]
