# Generated by Django 6.0.1 on 2026-02-02 17:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_auto_detect_current_academic_year"),
    ]

    operations = [
        # First, remove the old unique_together constraint
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together=set(),  # Remove existing constraint first
        ),
        # Remove old fields from Semester that are no longer needed
        migrations.RemoveField(
            model_name="semester",
            name="is_current",
        ),
        migrations.RemoveField(
            model_name="semester",
            name="semester_type",
        ),
        # Add new fields to Semester
        migrations.AddField(
            model_name="semester",
            name="year_of_study",
            field=models.IntegerField(
                choices=[
                    (1, "1st Year"),
                    (2, "2nd Year"),
                    (3, "3rd Year"),
                    (4, "4th Year"),
                ],
                default=1,
                help_text="Which year students this semester is for",
            ),
        ),
        # Update semester_number field
        migrations.AlterField(
            model_name="semester",
            name="semester_number",
            field=models.IntegerField(
                choices=[
                    (1, "Semester 1"),
                    (2, "Semester 2"),
                    (3, "Semester 3"),
                    (4, "Semester 4"),
                    (5, "Semester 5"),
                    (6, "Semester 6"),
                    (7, "Semester 7"),
                    (8, "Semester 8"),
                ],
                help_text="Semester 1-8",
            ),
        ),
        # Now set the new unique_together constraint
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "year_of_study", "semester_number")},
        ),
        # Update meta options for Semester
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": ["-academic_year", "year_of_study", "semester_number"],
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
            },
        ),
        # Update AcademicYear - remove dates, add new fields
        migrations.RemoveField(
            model_name="academicyear",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="academicyear",
            name="start_date",
        ),
        migrations.AddField(
            model_name="academicyear",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="academicyear",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelOptions(
            name="academicyear",
            options={
                "ordering": ["-year"],
                "verbose_name": "Academic Year",
                "verbose_name_plural": "Academic Years",
            },
        ),
    ]
