# Generated by Django 4.2.9 on 2026-02-05 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_add_answer_field_to_qpquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(verbose_name='Exam Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('duration_minutes', models.IntegerField(default=180, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='Duration (minutes)')),
                ('venue', models.CharField(blank=True, max_length=200, null=True, verbose_name='Exam Venue')),
                ('batch_labels', models.CharField(default='N,P,Q', help_text='Comma-separated batch labels (e.g., "N,P,Q")', max_length=20)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('ONGOING', 'Exam Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=15)),
                ('release_qp_after_exam', models.BooleanField(default=True, help_text='If checked, students can view QP after exam ends', verbose_name='Release QP to students after exam')),
                ('release_answers_after_exam', models.BooleanField(default=True, help_text='If checked, students can view answer key after exam ends', verbose_name='Release answers to students after exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_exams', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.semester')),
                ('structured_qp', models.OneToOneField(help_text='The approved question paper for this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedule', to='main_app.structuredquestionpaper')),
            ],
            options={
                'verbose_name': 'Exam Schedule',
                'verbose_name_plural': 'Exam Schedules',
                'db_table': 'main_app_examschedule',
                'ordering': ['-exam_date', '-start_time'],
            },
        ),
    ]
