# Generated by Django 6.0.1 on 2026-02-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0013_semester_year_of_study_restructure"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicyear",
            name="is_active",
        ),
    ]
