# Generated by Django 4.2.9 on 2026-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_exam_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='is_uploaded',
            field=models.BooleanField(default=False, help_text='True if QP was uploaded directly instead of created through structured form'),
        ),
        migrations.AddField(
            model_name='structuredquestionpaper',
            name='uploaded_document',
            field=models.FileField(blank=True, help_text='Directly uploaded question paper document', null=True, upload_to='question_papers/uploads/%Y/%m/'),
        ),
    ]
