# Generated by Django 6.0.1 on 2026-02-02 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0014_remove_academic_year_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="semester",
            options={
                "ordering": ["-academic_year", "semester_number"],
                "verbose_name": "Semester",
                "verbose_name_plural": "Semesters",
            },
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("academic_year", "semester_number")},
        ),
        migrations.RemoveField(
            model_name="semester",
            name="year_of_study",
        ),
    ]
