# Generated by Django 6.0.1 on 2026-02-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0015_remove_semester_year_of_study"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="graduation_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year of graduation (set when student completes 8th sem)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student_profile",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("GRADUATED", "Graduated"),
                    ("DROPPED", "Dropped Out"),
                    ("SUSPENDED", "Suspended"),
                    ("TRANSFERRED", "Transferred"),
                ],
                default="ACTIVE",
                max_length=15,
            ),
        ),
    ]
