# Generated by Django 6.0.1 on 2026-02-03 04:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_student_status_graduation"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegulationCoursePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "semester",
                    models.IntegerField(
                        help_text="Semester number (1-8)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("CSE", "Computer Science and Engineering"),
                            ("AIML", "Artificial Intelligence and Machine Learning"),
                            ("CSBS", "Computer Science and Business Systems"),
                        ],
                        default="CSE",
                        max_length=10,
                    ),
                ),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("UG", "Undergraduate"),
                            ("PG", "Postgraduate"),
                            ("PHD", "Ph.D."),
                        ],
                        default="UG",
                        max_length=5,
                    ),
                ),
                (
                    "is_elective",
                    models.BooleanField(
                        default=False, help_text="Is this an elective course?"
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True, help_text="Is this course mandatory?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulation_plans",
                        to="main_app.course",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_plans",
                        to="main_app.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Regulation Course Plan",
                "verbose_name_plural": "Regulation Course Plans",
                "ordering": ["regulation", "semester", "branch", "course"],
                "unique_together": {("regulation", "course", "branch", "program_type")},
            },
        ),
    ]
