# Generated by Django 6.0.1 on 2026-02-03 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0017_regulation_course_plan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="regulation",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="main_app.regulation",
            ),
        ),
    ]
