# Generated by Django 6.0.1 on 2026-02-03 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0018_remove_regulation_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["course_code"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="course",
            name="category",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_lab",
        ),
        migrations.RemoveField(
            model_name="course",
            name="regulation",
        ),
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
        migrations.AddField(
            model_name="regulationcourseplan",
            name="category",
            field=models.ForeignKey(
                blank=True,
                help_text="Course category (PCC, ESC, PEC, etc.)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_plans",
                to="main_app.coursecategory",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("LIT", "Lecture with Integrated Tutorial (L-T-0)"),
                    ("T", "Theory (L-0-0)"),
                    ("L", "Lab/Practical (0-0-P)"),
                    ("CDP", "Course Development Project (0-0-P)"),
                ],
                default="T",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="lecture_hours",
            field=models.IntegerField(
                default=3,
                help_text="L in L-T-P",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="practical_hours",
            field=models.IntegerField(
                default=0,
                help_text="P in L-T-P",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="tutorial_hours",
            field=models.IntegerField(
                default=0,
                help_text="T in L-T-P",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
