# Generated by Django 6.0.1 on 2026-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_course_model_restructure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("LIT", "Laboratory Integrated Theory"),
                    ("T", "Theory"),
                    ("L", "Laboratory Course"),
                    ("IPW", "Internship cum Project Work"),
                    ("PW", "Project Work"),
                    ("CDP", "Capstone Design Project"),
                ],
                default="T",
                max_length=10,
                null=True,
            ),
        ),
    ]
