# Generated by Django 6.0.1 on 2026-02-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_update_course_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulationcourseplan",
            name="branch",
            field=models.CharField(
                default="CSE",
                help_text="Program code from Program model",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="branch",
            field=models.CharField(
                default="CSE",
                help_text="Program code from Program model",
                max_length=20,
            ),
        ),
    ]
