# Generated by Django 6.0.1 on 2026-02-03 10:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0021_remove_hardcoded_branch_choices"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="course_assignment",
            name="batch_label",
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="batch_label",
            field=models.CharField(
                default="A", max_length=10, verbose_name="Classroom Section"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="batch",
            field=models.CharField(
                blank=True,
                help_text="Legacy field - use program_batch instead",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="ProgramBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        help_text="Year of study (1st year, 2nd year, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "batch_name",
                    models.CharField(
                        help_text="Batch/Section name (e.g., A, B, N, P, Q)",
                        max_length=10,
                    ),
                ),
                (
                    "batch_display",
                    models.CharField(
                        blank=True,
                        help_text="Display name (e.g., 'N Section')",
                        max_length=50,
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=60,
                        help_text="Maximum students in this batch",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_batches",
                        to="main_app.academicyear",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="main_app.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Batch",
                "verbose_name_plural": "Program Batches",
                "ordering": ["academic_year", "program", "year_of_study", "batch_name"],
                "unique_together": {
                    ("academic_year", "program", "year_of_study", "batch_name")
                },
            },
        ),
        migrations.AddField(
            model_name="course_assignment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_assignments",
                to="main_app.programbatch",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="program_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timetables",
                to="main_app.programbatch",
            ),
        ),
    ]
