# Generated by Django 6.0.1 on 2026-02-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_remove_hardcoded_batch_choices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="is_active",
        ),
    ]
