# Generated by Django 6.0.1 on 2026-02-03 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_remove_program_is_active_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="default_batch_count",
            field=models.IntegerField(
                default=3,
                help_text="Default number of batches for 1st year intake",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="default_batch_labels",
            field=models.CharField(
                blank=True,
                default="A,B,C",
                help_text="Default batch names separated by comma (e.g., A,B,C or N,P,Q)",
                max_length=50,
            ),
        ),
    ]
