# Generated by Django 6.0.1 on 2026-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0024_add_default_batch_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="regulationcourseplan",
            name="elective_vertical",
            field=models.CharField(
                blank=True,
                help_text="Elective vertical/specialization (e.g., 'Data Science', 'Cloud Computing')",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="degree",
            field=models.CharField(
                choices=[
                    ("BE", "B.E."),
                    ("BTECH", "B.Tech."),
                    ("ME", "M.E."),
                    ("MTECH", "M.Tech."),
                    ("MS", "M.S."),
                ],
                default="BE",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="level",
            field=models.CharField(
                choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                default="UG",
                max_length=5,
            ),
        ),
    ]
