# Generated by Django 6.0.1 on 2026-02-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0025_add_elective_vertical"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectiveVertical",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vertical name (e.g., 'Data Science', 'Cloud Computing')",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the vertical",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_verticals",
                        to="main_app.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elective Vertical",
                "verbose_name_plural": "Elective Verticals",
                "ordering": ["regulation", "name"],
                "unique_together": {("regulation", "name")},
            },
        ),
        migrations.AlterField(
            model_name="regulationcourseplan",
            name="elective_vertical",
            field=models.ForeignKey(
                blank=True,
                help_text="Elective vertical/specialization",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="course_plans",
                to="main_app.electivevertical",
            ),
        ),
    ]
