# Generated by Django 6.0.1 on 2026-02-06 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0026_elective_vertical_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="True for slots like PEC-I, OEC-I that get filled later",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="placeholder_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PEC", "Professional Elective Course"),
                    ("OEC", "Open Elective Course"),
                    ("SDC", "Skill Development Course"),
                    ("SLC", "Self Learning Course"),
                    ("IOC", "Industry Oriented Course"),
                    ("AC", "Audit Course"),
                    ("ETC", "Emerging Technology Course"),
                    ("NCC", "NCC/NSS/NSO/YRC"),
                    ("HON", "Honours Elective"),
                    ("MIN", "Minor Elective"),
                ],
                help_text="Type of placeholder (PEC, OEC, SDC, etc.)",
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="slot_number",
            field=models.IntegerField(
                blank=True,
                help_text="Slot number for placeholders (1 for PEC-I, 2 for PEC-II, etc.)",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ElectiveCourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_count",
                    models.IntegerField(
                        default=1,
                        help_text="Number of batches for this course offering",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "capacity_per_batch",
                    models.IntegerField(
                        default=60,
                        help_text="Maximum students per batch",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actual_course",
                    models.ForeignKey(
                        help_text="The actual course (e.g., CS23001 - Data Mining)",
                        limit_choices_to={"is_placeholder": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_offerings",
                        to="main_app.course",
                    ),
                ),
                (
                    "elective_vertical",
                    models.ForeignKey(
                        blank=True,
                        help_text="Elective vertical this course belongs to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_offerings",
                        to="main_app.electivevertical",
                    ),
                ),
                (
                    "regulation_course_plan",
                    models.ForeignKey(
                        help_text="The placeholder slot (e.g., PEC-I in Sem 5)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_offerings",
                        to="main_app.regulationcourseplan",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        help_text="Academic semester (e.g., 2025-26 Sem 5)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_offerings",
                        to="main_app.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elective Course Offering",
                "verbose_name_plural": "Elective Course Offerings",
                "ordering": ["semester", "regulation_course_plan", "actual_course"],
                "unique_together": {
                    ("regulation_course_plan", "semester", "actual_course")
                },
            },
        ),
    ]
