# Generated by Django 6.0.1 on 2026-02-07 07:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0027_placeholder_courses_and_offerings"),
    ]

    operations = [
        migrations.CreateModel(
            name="StructuredQuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exam_month_year",
                    models.CharField(
                        help_text="e.g., NOV/DEC 2023",
                        max_length=50,
                        verbose_name="Exam Month/Year",
                    ),
                ),
                (
                    "co1_description",
                    models.TextField(blank=True, verbose_name="CO1 Description"),
                ),
                (
                    "co2_description",
                    models.TextField(blank=True, verbose_name="CO2 Description"),
                ),
                (
                    "co3_description",
                    models.TextField(blank=True, verbose_name="CO3 Description"),
                ),
                (
                    "co4_description",
                    models.TextField(blank=True, verbose_name="CO4 Description"),
                ),
                (
                    "co5_description",
                    models.TextField(blank=True, verbose_name="CO5 Description"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted for Review"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("hod_comments", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "generated_document",
                    models.FileField(
                        blank=True,
                        help_text="Auto-generated .docx file in R2023 format",
                        null=True,
                        upload_to="question_papers/structured/%Y/%m/",
                    ),
                ),
                (
                    "uploaded_document",
                    models.FileField(
                        blank=True,
                        help_text="Directly uploaded question paper document",
                        null=True,
                        upload_to="question_papers/uploads/%Y/%m/",
                    ),
                ),
                (
                    "is_uploaded",
                    models.BooleanField(
                        default=False,
                        help_text="True if QP was uploaded directly instead of created through structured form",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.academicyear",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structured_qps",
                        to="main_app.faculty_profile",
                    ),
                ),
                (
                    "qp_assignment",
                    models.OneToOneField(
                        blank=True,
                        help_text="Optional link to question paper assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="structured_qp",
                        to="main_app.questionpaperassignment",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.regulation",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_qps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Structured Question Paper",
                "verbose_name_plural": "Structured Question Papers",
                "db_table": "main_app_structuredquestionpaper",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QPQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part",
                    models.CharField(
                        choices=[
                            ("A", "Part A - Short Answer (2 marks)"),
                            ("B", "Part B - Descriptive (13 marks)"),
                            ("C", "Part C - Problem Solving (15 marks)"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "question_number",
                    models.IntegerField(help_text="Question number (1-16)"),
                ),
                ("is_or_option", models.BooleanField(default=False)),
                (
                    "or_pair_number",
                    models.IntegerField(
                        blank=True,
                        help_text="For Part B: 11, 12, 13, 14, 15",
                        null=True,
                    ),
                ),
                (
                    "option_label",
                    models.CharField(
                        blank=True, help_text="(a) or (b) for OR options", max_length=5
                    ),
                ),
                ("question_text", models.TextField(help_text="Main question text")),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="Selected answer for answer key"
                    ),
                ),
                ("has_subdivisions", models.BooleanField(default=False)),
                ("subdivision_1_text", models.TextField(blank=True)),
                ("subdivision_1_marks", models.IntegerField(blank=True, null=True)),
                ("subdivision_2_text", models.TextField(blank=True)),
                ("subdivision_2_marks", models.IntegerField(blank=True, null=True)),
                (
                    "course_outcome",
                    models.CharField(
                        choices=[
                            ("CO1", "CO1"),
                            ("CO2", "CO2"),
                            ("CO3", "CO3"),
                            ("CO4", "CO4"),
                            ("CO5", "CO5"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "bloom_level",
                    models.CharField(
                        choices=[
                            ("L1", "L1 - Remember"),
                            ("L2", "L2 - Understand"),
                            ("L3", "L3 - Apply"),
                            ("L4", "L4 - Analyze"),
                            ("L5", "L5 - Evaluate"),
                            ("L6", "L6 - Create"),
                        ],
                        max_length=5,
                    ),
                ),
                ("marks", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question_paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="main_app.structuredquestionpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Paper Question",
                "verbose_name_plural": "Question Paper Questions",
                "db_table": "main_app_qpquestion",
                "ordering": ["part", "question_number", "option_label"],
            },
        ),
        migrations.CreateModel(
            name="ExamSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exam_date", models.DateField(verbose_name="Exam Date")),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=180,
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="Duration (minutes)",
                    ),
                ),
                (
                    "venue",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Exam Venue"
                    ),
                ),
                (
                    "batch_labels",
                    models.CharField(
                        default="N,P,Q",
                        help_text='Comma-separated batch labels (e.g., "N,P,Q")',
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Exam Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=15,
                    ),
                ),
                (
                    "release_qp_after_exam",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, students can view QP after exam ends",
                        verbose_name="Release QP to students after exam",
                    ),
                ),
                (
                    "release_answers_after_exam",
                    models.BooleanField(
                        default=True,
                        help_text="If checked, students can view answer key after exam ends",
                        verbose_name="Release answers to students after exam",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scheduled_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scheduled_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.semester",
                    ),
                ),
                (
                    "structured_qp",
                    models.OneToOneField(
                        help_text="The approved question paper for this exam",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_schedule",
                        to="main_app.structuredquestionpaper",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exam Schedule",
                "verbose_name_plural": "Exam Schedules",
                "db_table": "main_app_examschedule",
                "ordering": ["-exam_date", "-start_time"],
            },
        ),
    ]
