# Generated by Django 6.0.1 on 2026-02-08 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_structuredquestionpaper_qpquestion_examschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="student_profile",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular Entry (1st Semester)"),
                    ("LATERAL", "Lateral Entry (3rd Semester)"),
                ],
                default="REGULAR",
                help_text="Regular = joined in 1st sem, Lateral = joined in 3rd sem",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="admission_year",
            field=models.IntegerField(
                blank=True, help_text="Calendar year of admission", null=True
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="batch_label",
            field=models.CharField(
                default="A",
                help_text="Must be one of the labels from admission_batch.batch_labels",
                max_length=10,
                verbose_name="Classroom Section",
            ),
        ),
        migrations.CreateModel(
            name="AdmissionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admission_year",
                    models.IntegerField(
                        help_text="Calendar year of admission (e.g., 2024, 2025)",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("REGULAR", "Regular Entry (1st Semester)"),
                            ("LATERAL", "Lateral Entry (3rd Semester)"),
                        ],
                        default="REGULAR",
                        help_text="Regular = 1st sem freshers, Lateral = 3rd sem direct entry",
                        max_length=10,
                    ),
                ),
                (
                    "batch_labels",
                    models.CharField(
                        default="A,B,C",
                        help_text="Comma-separated batch labels (e.g., 'A,B,C' or 'N,P,Q' or 'L1,L2' for lateral)",
                        max_length=100,
                    ),
                ),
                (
                    "capacity_per_batch",
                    models.IntegerField(
                        default=60,
                        help_text="Maximum students per batch/section",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this admission batch",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_batches",
                        to="main_app.program",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        blank=True,
                        help_text="Regulation under which this batch studies",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admission_batches",
                        to="main_app.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admission Batch",
                "verbose_name_plural": "Admission Batches",
                "ordering": ["-admission_year", "program", "entry_type"],
                "unique_together": {("program", "admission_year", "entry_type")},
            },
        ),
        migrations.AddField(
            model_name="student_profile",
            name="admission_batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The admission batch/cohort this student belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="main_app.admissionbatch",
            ),
        ),
    ]
