# Generated by Django 6.0.1 on 2026-02-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_admission_batch_system"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admissionbatch",
            options={
                "ordering": ["-admission_year", "program"],
                "verbose_name": "Admission Batch",
                "verbose_name_plural": "Admission Batches",
            },
        ),
        migrations.AlterUniqueTogether(
            name="admissionbatch",
            unique_together={("program", "admission_year")},
        ),
        migrations.AddField(
            model_name="admissionbatch",
            name="lateral_intake_per_batch",
            field=models.IntegerField(
                default=10,
                help_text="Maximum lateral entry students per batch (UG only). Set to 0 to disable lateral entry.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="admissionbatch",
            name="batch_labels",
            field=models.CharField(
                default="A,B,C",
                help_text="Comma-separated batch labels (e.g., 'A,B,C' or 'N,P,Q')",
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="admissionbatch",
            name="entry_type",
        ),
    ]
