# Generated by Django 6.0.1 on 2026-02-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0030_remove_lateral_batch_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_profile",
            name="batch_label",
            field=models.CharField(
                blank=True,
                help_text="Must be one of the labels from admission_batch.batch_labels",
                max_length=10,
                verbose_name="Classroom Section",
            ),
        ),
        migrations.AlterField(
            model_name="student_profile",
            name="branch",
            field=models.CharField(
                blank=True, help_text="Program code from Program model", max_length=20
            ),
        ),
    ]
