# Generated by Django 6.0.1 on 2026-02-08 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0031_remove_hardcoded_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_assignment",
            name="lab_assistant",
            field=models.ForeignKey(
                blank=True,
                help_text="Lab assistant (faculty) for L/LIT courses",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lab_assistant_assignments",
                to="main_app.faculty_profile",
            ),
        ),
    ]
