# Generated by Django 6.0.1 on 2026-02-08 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0032_course_assignment_lab_assistant"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectiveOfferingFacultyAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_number",
                    models.IntegerField(
                        help_text="Batch number (1, 2, 3, etc.)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        help_text="Faculty assigned to this batch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elective_assignments",
                        to="main_app.faculty_profile",
                    ),
                ),
                (
                    "lab_assistant",
                    models.ForeignKey(
                        blank=True,
                        help_text="Lab assistant for L/LIT courses",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="elective_lab_assistant_assignments",
                        to="main_app.faculty_profile",
                    ),
                ),
                (
                    "offering",
                    models.ForeignKey(
                        help_text="The elective course offering",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faculty_assignments",
                        to="main_app.electivecourseoffering",
                    ),
                ),
            ],
            options={
                "verbose_name": "Elective Offering Faculty Assignment",
                "verbose_name_plural": "Elective Offering Faculty Assignments",
                "ordering": ["offering", "batch_number"],
                "unique_together": {("offering", "batch_number")},
            },
        ),
    ]
