# Generated by Django 6.0.1 on 2026-02-08 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0033_elective_offering_faculty_assignment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="regulations",
        ),
        migrations.AddField(
            model_name="program",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                help_text="Regulation under which this program is offered",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="main_app.regulation",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="code",
            field=models.CharField(
                help_text="e.g., CSE, CSE-OR, CSE-BDA, SE", max_length=20
            ),
        ),
        migrations.AddConstraint(
            model_name="program",
            constraint=models.UniqueConstraint(
                fields=("code", "regulation"), name="unique_program_code_per_regulation"
            ),
        ),
    ]
