# Generated by Django 6.0.1 on 2026-02-08 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0034_program_regulation_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_profile",
            name="register_no",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Register number must be exactly 10 digits",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Register Number",
            ),
        ),
    ]
