# Generated by Django 6.0.1 on 2026-02-10 18:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0035_fix_register_no_10digits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="regulation",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED - Use ProgramRegulation model instead",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="programs_deprecated",
                to="main_app.regulation",
            ),
        ),
        migrations.CreateModel(
            name="ProgramRegulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "effective_from_year",
                    models.IntegerField(
                        help_text="First admission year this regulation applies to",
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "effective_to_year",
                    models.IntegerField(
                        blank=True,
                        help_text="Last admission year this applies to (NULL = still active)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this mapping is currently active",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any notes about this regulation mapping"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        help_text="The academic program",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regulation_mappings",
                        to="main_app.program",
                    ),
                ),
                (
                    "regulation",
                    models.ForeignKey(
                        help_text="The regulation/curriculum this program follows",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_mappings",
                        to="main_app.regulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Regulation Mapping",
                "verbose_name_plural": "Program Regulation Mappings",
                "ordering": ["program", "-effective_from_year"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "regulation"),
                        name="unique_program_regulation_mapping",
                    )
                ],
            },
        ),
    ]
