# Generated by Django 6.0.1 on 2026-02-22 16:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0036_program_regulation_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., CASE Tools Lab, Programming Lab",
                        max_length=100,
                    ),
                ),
                (
                    "room_code",
                    models.CharField(
                        help_text="e.g., LAB-01, LAB-02", max_length=20, unique=True
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        default=60,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lab Room",
                "verbose_name_plural": "Lab Rooms",
                "ordering": ["room_code"],
            },
        ),
        migrations.CreateModel(
            name="TimetableConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_generated",
                    models.BooleanField(
                        default=False,
                        help_text="True once timetables have been generated from this config",
                    ),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_configs",
                        to="main_app.academicyear",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_configs",
                        to="main_app.program",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timetable_configs",
                        to="main_app.semester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timetable Config",
                "verbose_name_plural": "Timetable Configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_of_study",
                    models.IntegerField(
                        blank=True,
                        help_text="Restrict to this year (null = all years)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict to this program (null = any program)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.program",
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to="main_app.labroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Restriction",
                "verbose_name_plural": "Lab Restrictions",
                "ordering": ["lab", "program", "year_of_study"],
                "unique_together": {("lab", "program", "year_of_study")},
            },
        ),
        migrations.CreateModel(
            name="FixedSlotReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "special_note",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "apply_to_all_batches",
                    models.BooleanField(
                        default=False,
                        help_text="If True, this same course+slot applies to all batches of this program+year",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slot_reservations",
                        to="main_app.programbatch",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.course",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main_app.faculty_profile",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main_app.timeslot",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="main_app.timetableconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fixed Slot Reservation",
                "verbose_name_plural": "Fixed Slot Reservations",
                "ordering": ["batch", "day", "time_slot"],
                "unique_together": {("config", "batch", "day", "time_slot")},
            },
        ),
    ]
